name: meal_monkey
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  custom_clippers: ^2.0.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/real/
    - assets/images/virtual/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.ttf
        - asset: assets/fonts/Metropolis-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Metropolis-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Metropolis-ExtraBoldItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Metropolis-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Metropolis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Metropolis-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: SocialMedia
      fonts:
        - asset: assets/icons/google.ttf
